/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tool.csv;

import static com.tool.csv.MainFrame.active_smell;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author Bilal
 */
public class Shotgun_Threshold extends javax.swing.JDialog {

    /**
     * Creates new form LargeClassThreshold
     */
    public static int var_lower_low;
    public static int var_lower_up;
    public static int var_med_low;
    public static int var_med_up;
    public static int var_high_low;
    public static int method_lower_low;
    public static int method_lower_up;
    public static int method_med_low;
    public static int method_med_up;
    public static int method_high_low;
    public Shotgun_Threshold(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/com/tool/csv/insect-icon.png")).getImage());
        reset_btn3ActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField_LowImpact_low = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_LowImpact_up = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jTextField_MedImpact_low = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_MedImpact_up = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField_HighImpact_low = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_HighImpact_up = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextField_LowImpact_low1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_LowImpact_up1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jTextField_MedImpact_low1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_MedImpact_up1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextField_HighImpact_low1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_HighImpact_up1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        reset_btn2 = new javax.swing.JButton();
        reset_btn3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set Threshold Value For ShotgunSurgery Bad Smell");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Set Threshold Value ");

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Number of Defined Methods", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Low Impact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N

        jTextField_LowImpact_low.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_LowImpact_lowFocusLost(evt);
            }
        });
        jTextField_LowImpact_low.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_LowImpact_lowKeyTyped(evt);
            }
        });

        jLabel9.setText("Lower Limit:");

        jTextField_LowImpact_up.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_LowImpact_upFocusLost(evt);
            }
        });
        jTextField_LowImpact_up.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_LowImpact_upKeyTyped(evt);
            }
        });

        jLabel3.setText("Upper Limit:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_LowImpact_low, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_LowImpact_up)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_LowImpact_low, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_LowImpact_up, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel10.add(jPanel3);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Medium Impact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N

        jTextField_MedImpact_low.setEditable(false);
        jTextField_MedImpact_low.setFocusable(false);
        jTextField_MedImpact_low.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_MedImpact_lowFocusLost(evt);
            }
        });

        jLabel4.setText("Lower Limit:");

        jTextField_MedImpact_up.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_MedImpact_upFocusLost(evt);
            }
        });
        jTextField_MedImpact_up.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_MedImpact_upKeyTyped(evt);
            }
        });

        jLabel5.setText("Upper Limit:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_MedImpact_low, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_MedImpact_up)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_MedImpact_low, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_MedImpact_up, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel10.add(jPanel11);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "High Impact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N

        jTextField_HighImpact_low.setEditable(false);
        jTextField_HighImpact_low.setFocusable(false);
        jTextField_HighImpact_low.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_HighImpact_lowFocusLost(evt);
            }
        });

        jLabel6.setText("Lower Limit:");

        jTextField_HighImpact_up.setEditable(false);
        jTextField_HighImpact_up.setFocusable(false);

        jLabel7.setText("Upper Limit:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_HighImpact_low, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_HighImpact_up)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_HighImpact_low, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_HighImpact_up, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel10.add(jPanel5);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Number of Calling Methods", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Low Impact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N

        jTextField_LowImpact_low1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_LowImpact_low1FocusLost(evt);
            }
        });
        jTextField_LowImpact_low1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_LowImpact_low1KeyTyped(evt);
            }
        });

        jLabel10.setText("Lower Limit:");

        jTextField_LowImpact_up1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_LowImpact_up1FocusLost(evt);
            }
        });
        jTextField_LowImpact_up1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_LowImpact_up1KeyTyped(evt);
            }
        });

        jLabel8.setText("Upper Limit:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_LowImpact_low1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_LowImpact_up1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_LowImpact_low1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_LowImpact_up1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel12.add(jPanel4);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Medium Impact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N

        jTextField_MedImpact_low1.setEditable(false);
        jTextField_MedImpact_low1.setFocusable(false);
        jTextField_MedImpact_low1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_MedImpact_low1FocusLost(evt);
            }
        });

        jLabel11.setText("Lower Limit:");

        jTextField_MedImpact_up1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_MedImpact_up1FocusLost(evt);
            }
        });
        jTextField_MedImpact_up1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_MedImpact_up1KeyTyped(evt);
            }
        });

        jLabel12.setText("Upper Limit:");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_MedImpact_low1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_MedImpact_up1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_MedImpact_low1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_MedImpact_up1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel12.add(jPanel13);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "High Impact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N

        jTextField_HighImpact_low1.setEditable(false);
        jTextField_HighImpact_low1.setFocusable(false);
        jTextField_HighImpact_low1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_HighImpact_low1FocusLost(evt);
            }
        });

        jLabel13.setText("Lower Limit:");

        jTextField_HighImpact_up1.setEditable(false);
        jTextField_HighImpact_up1.setFocusable(false);

        jLabel14.setText("Upper Limit:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_HighImpact_low1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_HighImpact_up1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_HighImpact_low1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_HighImpact_up1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel12.add(jPanel6);

        reset_btn2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        reset_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tool/csv/Ok-icon.png"))); // NOI18N
        reset_btn2.setText("OK");
        reset_btn2.setIconTextGap(8);
        reset_btn2.setPreferredSize(new java.awt.Dimension(80, 35));
        reset_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btn2ActionPerformed(evt);
            }
        });

        reset_btn3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        reset_btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tool/csv/reset.png"))); // NOI18N
        reset_btn3.setText("Reset");
        reset_btn3.setIconTextGap(8);
        reset_btn3.setPreferredSize(new java.awt.Dimension(80, 35));
        reset_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(reset_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reset_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private boolean isTextFieldEmpty()
    {
        if(jTextField_LowImpact_low.getText().isEmpty() || jTextField_LowImpact_up.getText().isEmpty()
                || jTextField_MedImpact_low.getText().isEmpty() || jTextField_MedImpact_up.getText().isEmpty()
                || jTextField_HighImpact_low.getText().isEmpty() || jTextField_HighImpact_up.getText().isEmpty()
                || jTextField_LowImpact_low1.getText().isEmpty() || jTextField_LowImpact_up1.getText().isEmpty()
                || jTextField_MedImpact_low1.getText().isEmpty() || jTextField_MedImpact_up1.getText().isEmpty()
                || jTextField_HighImpact_low1.getText().isEmpty() || jTextField_HighImpact_up1.getText().isEmpty())
        {
            return true;
        }
        else
            return false;
    }
    
    private boolean checkThresholdLimit()
    {
        if(!isTextFieldEmpty())
        {
            if((Integer.parseInt(jTextField_LowImpact_low.getText()) > Integer.parseInt(jTextField_LowImpact_up.getText()))
                    || (Integer.parseInt(jTextField_MedImpact_low.getText()) > Integer.parseInt(jTextField_MedImpact_up.getText()))
                    || (Integer.parseInt(jTextField_LowImpact_low1.getText()) > Integer.parseInt(jTextField_LowImpact_up1.getText()))
                    || (Integer.parseInt(jTextField_MedImpact_low1.getText()) > Integer.parseInt(jTextField_MedImpact_up1.getText())))
            {
                return false;
            }
            else
            {
                return true;
            }
                    
        }
        else{
            return false;
        }
    }
    private void jTextField_LowImpact_lowFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_LowImpact_lowFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_LowImpact_lowFocusLost

    private void jTextField_LowImpact_upFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_LowImpact_upFocusLost
        // TODO add your handling code here:
        if(!jTextField_LowImpact_up.getText().isEmpty())
        {
            int val = Integer.parseInt(jTextField_LowImpact_up.getText());
                jTextField_MedImpact_low.setText(""+(val+1));
                jTextField_MedImpact_up.requestFocus();
            
        }
    }//GEN-LAST:event_jTextField_LowImpact_upFocusLost

    private void jTextField_MedImpact_lowFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_MedImpact_lowFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MedImpact_lowFocusLost

    private void jTextField_MedImpact_upFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_MedImpact_upFocusLost
        // TODO add your handling code here:
        if(!jTextField_MedImpact_up.getText().isEmpty())
        {
            int val = Integer.parseInt(jTextField_MedImpact_up.getText());
            jTextField_HighImpact_low.setText(""+(val+1));
        }
        
    }//GEN-LAST:event_jTextField_MedImpact_upFocusLost

    private void jTextField_HighImpact_lowFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_HighImpact_lowFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_HighImpact_lowFocusLost

    private void jTextField_LowImpact_low1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_LowImpact_low1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LowImpact_low1FocusLost

    private void jTextField_LowImpact_up1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_LowImpact_up1FocusLost
        // TODO add your handling code here:
        if(!jTextField_LowImpact_up1.getText().isEmpty())
        {
            int val = Integer.parseInt(jTextField_LowImpact_up1.getText());
            jTextField_MedImpact_low1.setText(""+(val+1));
                jTextField_MedImpact_up1.requestFocus();
            
        }
    }//GEN-LAST:event_jTextField_LowImpact_up1FocusLost

    private void jTextField_MedImpact_low1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_MedImpact_low1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MedImpact_low1FocusLost

    private void jTextField_MedImpact_up1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_MedImpact_up1FocusLost
        // TODO add your handling code here:
        if(!jTextField_MedImpact_up1.getText().isEmpty())
        {
            int val = Integer.parseInt(jTextField_MedImpact_up1.getText());
            jTextField_HighImpact_low1.setText(""+(val+1));
        }
    }//GEN-LAST:event_jTextField_MedImpact_up1FocusLost

    private void jTextField_HighImpact_low1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_HighImpact_low1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_HighImpact_low1FocusLost

    private void reset_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btn2ActionPerformed
        // TODO add your handling code here:
        if(!isTextFieldEmpty() && checkThresholdLimit())
        {
            var_lower_low = Integer.parseInt(jTextField_LowImpact_low.getText());
            var_lower_up = Integer.parseInt(jTextField_LowImpact_up.getText());
            var_med_low = Integer.parseInt(jTextField_MedImpact_low.getText());
            var_med_up = Integer.parseInt(jTextField_MedImpact_up.getText());
            var_high_low = Integer.parseInt(jTextField_HighImpact_low.getText());
            method_lower_low = Integer.parseInt(jTextField_LowImpact_low1.getText());
            method_lower_up = Integer.parseInt(jTextField_LowImpact_up1.getText());
            method_med_low = Integer.parseInt(jTextField_MedImpact_low1.getText());
            method_med_up = Integer.parseInt(jTextField_MedImpact_up1.getText());
            method_high_low = Integer.parseInt(jTextField_HighImpact_low1.getText());
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "Fill All fields.\nOR\nCheck Threshold Limit.","Information",JOptionPane.INFORMATION_MESSAGE);
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_reset_btn2ActionPerformed

    private void reset_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btn3ActionPerformed
        // TODO add your handling code here:
        jTextField_LowImpact_low.setText("6");
        jTextField_LowImpact_up.setText("10");
        jTextField_MedImpact_low.setText("11");
        jTextField_MedImpact_up.setText("15");
        jTextField_HighImpact_low.setText("16");
        jTextField_HighImpact_up.setText("So on..");
        jTextField_LowImpact_low1.setText("6");
        jTextField_LowImpact_up1.setText("10");
        jTextField_MedImpact_low1.setText("11");
        jTextField_MedImpact_up1.setText("15");
        jTextField_HighImpact_low1.setText("16");
        jTextField_HighImpact_up1.setText("So on..");
    }//GEN-LAST:event_reset_btn3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        reset_btn2ActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    private void jTextField_LowImpact_lowKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_LowImpact_lowKeyTyped
        // TODO add your handling code here:
        new MainFrame().integerConstraint(evt);
    }//GEN-LAST:event_jTextField_LowImpact_lowKeyTyped

    private void jTextField_LowImpact_upKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_LowImpact_upKeyTyped
        // TODO add your handling code here:
        new MainFrame().integerConstraint(evt);
    }//GEN-LAST:event_jTextField_LowImpact_upKeyTyped

    private void jTextField_MedImpact_upKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_MedImpact_upKeyTyped
        // TODO add your handling code here:
        new MainFrame().integerConstraint(evt);
    }//GEN-LAST:event_jTextField_MedImpact_upKeyTyped

    private void jTextField_LowImpact_low1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_LowImpact_low1KeyTyped
        // TODO add your handling code here:
        new MainFrame().integerConstraint(evt);
    }//GEN-LAST:event_jTextField_LowImpact_low1KeyTyped

    private void jTextField_LowImpact_up1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_LowImpact_up1KeyTyped
        // TODO add your handling code here:
        new MainFrame().integerConstraint(evt);
    }//GEN-LAST:event_jTextField_LowImpact_up1KeyTyped

    private void jTextField_MedImpact_up1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_MedImpact_up1KeyTyped
        // TODO add your handling code here:
        new MainFrame().integerConstraint(evt);
    }//GEN-LAST:event_jTextField_MedImpact_up1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LargeClassThreshold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LargeClassThreshold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LargeClassThreshold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LargeClassThreshold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LargeClassThreshold dialog = new LargeClassThreshold(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField_HighImpact_low;
    private javax.swing.JTextField jTextField_HighImpact_low1;
    private javax.swing.JTextField jTextField_HighImpact_up;
    private javax.swing.JTextField jTextField_HighImpact_up1;
    private javax.swing.JTextField jTextField_LowImpact_low;
    private javax.swing.JTextField jTextField_LowImpact_low1;
    private javax.swing.JTextField jTextField_LowImpact_up;
    private javax.swing.JTextField jTextField_LowImpact_up1;
    private javax.swing.JTextField jTextField_MedImpact_low;
    private javax.swing.JTextField jTextField_MedImpact_low1;
    private javax.swing.JTextField jTextField_MedImpact_up;
    private javax.swing.JTextField jTextField_MedImpact_up1;
    private javax.swing.JButton reset_btn2;
    private javax.swing.JButton reset_btn3;
    // End of variables declaration//GEN-END:variables
}
